name: Comment when opened
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Comment on latests commit
      #Add comment on last commit
        run: gh api repos/${{ github.repository }}/commits/${{ github.sha }}/comments -f body="Thanks for pushing your code!"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

