name: Comment when opened
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Comment on latests commit
      #Add comment on last commit
        run: gh issue list > issues.html
        
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

