name: Comment when opened
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Comment on latests commit
      #Add comment on issue
        run: gh issue comment 1 --body "This is a comment from the workflow!"
        
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

